### PR TITLE
Changing background color

### PR DESCRIPTION
**Pull request by Drunken-Sailor7**
Changing background colour from orange of unknown source to match the header colour of the InternationalSWS

### CODE REVIEW

**Comment by Kenny2github** [comment]
Could you include a screenshot so we can see the effects of the change better?

**Review by LiFaytheGoblin — COMMENTED** [review]
looks good to me

**Comment by Drunken-Sailor7** [comment]
> 
> 
> Could you include a screenshot so we can see the effects of the change better?

Of course

Current colour:
image

Suggested colour:
image

Current header on English Wiki:
image

**Comment by Kenny2github** [comment]
Pulled to production, thanks for the PR!

**Pull request merged**
